### ISSUE TITLE
Question : project ended ?

### ISSUE THREAD

**Issue by joeblew99** [ddf-project/DDF#271]
I am looking for a framework to help with ML of data in both batch and streaming scenarios.
This DDF looks very very simple to us, but there have been no issues closed for months ?
I would like to know if the project is dead.

Thanks in advance

**Comment by sameerp** [comment]
Hi Joe,

The project is very much alive and in active development. We are in the process of reworking some APIs and adding support for additional data stores.

**Comment by joeblew99** [comment]
But there are no closed issues for months ??

**Comment by ctn** [comment]
Yes, issue closure hygiene hasn't been so good. There's been a steady flow of PRs though.
