### ISSUE TITLE
DDF as a SpreadSheet with Cells, Rows, Columns defined through Formulas / Functions which update when when the DF data changes or accessed

### ISSUE THREAD

**Issue by sirinath** [ddf-project/DDF#59]
Being able to treat a DDF as a spread sheet with rows, columns, and cells defined through formulas / functions which update when internal DF data changes or accessed. This would increase the usefulness and power of DDF.

Have a look at the following projects to get an idea:
 - FlowSheet - http://www.ankhor.com/
 - Matrex - http://matrex.sourceforge.net/

If this is coupled with the functionality where you can define a new DF through a formula using multiple DFs and DF operations which update when data changes, this would make DDF very powerful. (https://github.com/ddf-project/DDF/issues/56) 

in this case the readable view of the DF should be different from the writeable view of the DF so combining DF will not mess up rows and columns calculated by formulas.

**Comment by ctn** [comment]
Adatao is doing something like this at the visualization layer, which is proprietary. We'll see what we can open source, perhaps as a reference implementation. cc @binhmop @mbbui .
